In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Social_Network_Ads.csv")
df

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [5]:
df.shape

(400, 5)

In [6]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [8]:
newdf = df.copy()

In [9]:
#import label encoder class
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()

In [11]:
newdf['Gender'] = le.fit_transform(newdf['Gender'])

In [12]:
newdf

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510       1  19.0          19000.0          0
1    15810944       1  35.0          20000.0          0
2    15668575       0  26.0          43000.0          0
3    15603246       0  27.0          57000.0          0
4    15804002       1  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863       0  46.0          41000.0          1
396  15706071       1  51.0          23000.0          1
397  15654296       0  50.0          20000.0          1
398  15755018       1  36.0          33000.0          0
399  15594041       0  49.0          36000.0          1

[400 rows x 5 columns]

In [13]:
le.classes_

array(['Female', 'Male'], dtype=object)

In [18]:
# one hot encoding

In [19]:
df = pd.get_dummies(df)

In [20]:
df

      User ID   Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510  19.0          19000.0          0              0            1
1    15810944  35.0          20000.0          0              0            1
2    15668575  26.0          43000.0          0              1            0
3    15603246  27.0          57000.0          0              1            0
4    15804002  19.0          76000.0          0              0            1
..        ...   ...              ...        ...            ...          ...
395  15691863  46.0          41000.0          1              1            0
396  15706071  51.0          23000.0          1              0            1
397  15654296  50.0          20000.0          1              1            0
398  15755018  36.0          33000.0          0              0            1
399  15594041  49.0          36000.0          1              1            0

[400 rows x 6 columns]

In [18]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

# Load dataset
df = sns.load_dataset('taxis')

# Remove pickup and dropoff columns
df = df.drop(columns=['pickup', 'dropoff'])

# Function to encode all categorical columns
def encode(df):
    le = LabelEncoder()

    for column in df.columns:
        if df[column].dtype == 'object' or str(df[column].dtype) == 'category':
            df[column] = le.fit_transform(df[column])

    return df

# Encode the dataset
newdf = encode(df)

print(newdf.head())

   passengers  distance  fare   tip  tolls  total  color  payment  \
0           1      1.60   7.0  2.15    0.0  12.95      1        1
1           1      0.79   5.0  0.00    0.0   9.30      1        0
2           1      1.37   7.5  2.36    0.0  14.16      1        1
3           1      7.70  27.0  6.15    0.0  36.95      1        1
4           3      2.16   9.0  1.10    0.0  13.40      1        1

   pickup_zone  dropoff_zone  pickup_borough  dropoff_borough
0           99           176               2                2
1          174           182               2                2
2            1           190               2                2
3           86           202               2                2
4          116           202               2                2

In [15]:
"""
load the taxis datasets from seaboarn
remove pickup and dropoff columns from the dataset
encode all the categorical columns using label encoding 
ideally create a function which encode when u pass the dataframe
""";

In [19]:
"""
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
df = df.copy()
df = sns.load_dataset('taxis');
df= newdf.drop(columns=['pickup', 'dropoff'])
def code(data):
    le = LabelEncoder()
    
    for columns in df.columns:
        if df[column].dtype == 'object' or str(df[column].dtype) == 'category':
            df[column] = le.fit_transform(df[column])
""";