In [1]:
import pandas as pd

In [6]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['sukanya','aish','laxmi','apurva','samruddhi'])
marks = pd.Series([85,87,84,87,79])

In [7]:
df = pd.DataFrame({
    'id' :roll,
    'name' : name,
    'marks': marks
})

In [8]:
df

   id       name  marks
0   1    sukanya     85
1   2       aish     87
2   3      laxmi     84
3   4     apurva     87
4   5  samruddhi     79

In [9]:
df.shape

(5, 3)

In [10]:
df.size

15

In [11]:
df.ndim

2

In [18]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [19]:
"""
url - > https://mitu.co.in/dataset



"""

'\nurl - > https://mitu.co.in/dataset\n\n\n\n'

In [20]:
pwd

'C:\\Users\\Pornima'

In [39]:
df = pd.read_csv("student.csv")

In [24]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [30]:
df = pd.read_csv("student1.csv")

In [31]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [32]:
col = ['roll','name','class','marks','age']

In [33]:
df = pd.read_csv('student1.csv',names =col)

In [34]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [44]:
df = pd.read_csv('student3.tsv', sep = '\t')
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21